describe("Count:", function()
   local Count = require("forget_me_not.count")
   it("construct count", function()
      local cnt = Count.new()
      assert.are.equal(cnt.value, 1)
      cnt = require("forget_me_not.count").new(15)
      assert.are.equal(cnt.value, 15)
   end)

   it("parse count", function()
      local cnt = Count.new()
      local str = "33j"
      local remain = cnt:parse(str)
      assert.are.equal(cnt.value, 33)
      assert.are.equal(remain, "j")
   end)
end)
